export const numbers = [
  { numerical: "0", spelledOut: "zero" },
  { numerical: "1", spelledOut: "one" },
  { numerical: "2", spelledOut: "two" },
  { numerical: "3", spelledOut: "three" },
  { numerical: "4", spelledOut: "four" },
  { numerical: "5", spelledOut: "five" },
  { numerical: "6", spelledOut: "six" },
  { numerical: "7", spelledOut: "seven" },
  { numerical: "8", spelledOut: "eight" },
  { numerical: "9", spelledOut: "nine" },
];

export const searchTerm = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "zero",
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
];
